//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contractor()
        {
            this.Delivery_Contract = new HashSet<Delivery_Contract>();
            this.Price_Reception = new HashSet<Price_Reception>();
        }
    
        public int contractor_id { get; set; }
        public string legal_contractor_address { get; set; }
        public string account_contractor_supplier_account { get; set; }
        public string surname_contractor { get; set; }
        public string contractor_name { get; set; }
        public string contractor_middle_name { get; set; }
        public string name_organization_contractor { get; set; }
        public string contractor_phone { get; set; }
        public string type_contractor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery_Contract> Delivery_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Reception> Price_Reception { get; set; }
    }
}
