//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery_Contract()
        {
            this.Reception_Invoice = new HashSet<Reception_Invoice>();
            this.Shipping_Invoice = new HashSet<Shipping_Invoice>();
        }
    
        public int delivery_contract_id { get; set; }
        public int contractor_id { get; set; }
        public System.DateTime contract_start_date { get; set; }
        public System.DateTime contract_end_date { get; set; }
        public decimal contract_cost { get; set; }
        public string validity { get; set; }
        public int number_of_contract_instances { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception_Invoice> Reception_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping_Invoice> Shipping_Invoice { get; set; }
    }
}
