//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dicomEntities : DbContext
    {
        public dicomEntities()
            : base("name=dicomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color_object> Color_object { get; set; }
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<Delivery_Contract> Delivery_Contract { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Measurement> Measurement { get; set; }
        public virtual DbSet<Price_Reception> Price_Reception { get; set; }
        public virtual DbSet<Price_Sendings> Price_Sendings { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_Location_Cell> Product_Location_Cell { get; set; }
        public virtual DbSet<Product_type> Product_type { get; set; }
        public virtual DbSet<Reception_Invoice> Reception_Invoice { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Shipping_Invoice> Shipping_Invoice { get; set; }
        public virtual DbSet<Storekeeper> Storekeeper { get; set; }
        public virtual DbSet<VAT> VAT { get; set; }
        public virtual DbSet<Reception_Specification> Reception_Specification { get; set; }
        public virtual DbSet<Shipping_Specification> Shipping_Specification { get; set; }
        public virtual DbSet<VIEWColor_object> VIEWColor_object { get; set; }
        public virtual DbSet<VIEWContractor> VIEWContractor { get; set; }
        public virtual DbSet<VIEWDelivery_Contract> VIEWDelivery_Contract { get; set; }
        public virtual DbSet<VIEWDelivery_Contract_P> VIEWDelivery_Contract_P { get; set; }
        public virtual DbSet<VIEWDelivery_Contract_Z> VIEWDelivery_Contract_Z { get; set; }
        public virtual DbSet<VIEWDiscount> VIEWDiscount { get; set; }
        public virtual DbSet<VIEWMaterials> VIEWMaterials { get; set; }
        public virtual DbSet<VIEWMeasurement> VIEWMeasurement { get; set; }
        public virtual DbSet<VIEWProduct> VIEWProduct { get; set; }
        public virtual DbSet<VIEWProduct_Location_Cell> VIEWProduct_Location_Cell { get; set; }
        public virtual DbSet<VIEWProduct_type> VIEWProduct_type { get; set; }
        public virtual DbSet<VIEWProduct2> VIEWProduct2 { get; set; }
        public virtual DbSet<VIEWReception_Invoice> VIEWReception_Invoice { get; set; }
        public virtual DbSet<VIEWRoles> VIEWRoles { get; set; }
        public virtual DbSet<VIEWShipping_Invoice> VIEWShipping_Invoice { get; set; }
        public virtual DbSet<VIEWStorekeeper> VIEWStorekeeper { get; set; }
        public virtual DbSet<VIEWStorekeeper2> VIEWStorekeeper2 { get; set; }
        public virtual DbSet<VIEWVAT> VIEWVAT { get; set; }
    
        public virtual int AddContractor(string legal_contractor_address, string account_contractor_supplier_account, string surname_contractor, string contractor_name, string contractor_middle_name, string name_organization_contractor, string contractor_phone, string type_contractor)
        {
            var legal_contractor_addressParameter = legal_contractor_address != null ?
                new ObjectParameter("legal_contractor_address", legal_contractor_address) :
                new ObjectParameter("legal_contractor_address", typeof(string));
    
            var account_contractor_supplier_accountParameter = account_contractor_supplier_account != null ?
                new ObjectParameter("account_contractor_supplier_account", account_contractor_supplier_account) :
                new ObjectParameter("account_contractor_supplier_account", typeof(string));
    
            var surname_contractorParameter = surname_contractor != null ?
                new ObjectParameter("surname_contractor", surname_contractor) :
                new ObjectParameter("surname_contractor", typeof(string));
    
            var contractor_nameParameter = contractor_name != null ?
                new ObjectParameter("contractor_name", contractor_name) :
                new ObjectParameter("contractor_name", typeof(string));
    
            var contractor_middle_nameParameter = contractor_middle_name != null ?
                new ObjectParameter("contractor_middle_name", contractor_middle_name) :
                new ObjectParameter("contractor_middle_name", typeof(string));
    
            var name_organization_contractorParameter = name_organization_contractor != null ?
                new ObjectParameter("name_organization_contractor", name_organization_contractor) :
                new ObjectParameter("name_organization_contractor", typeof(string));
    
            var contractor_phoneParameter = contractor_phone != null ?
                new ObjectParameter("contractor_phone", contractor_phone) :
                new ObjectParameter("contractor_phone", typeof(string));
    
            var type_contractorParameter = type_contractor != null ?
                new ObjectParameter("type_contractor", type_contractor) :
                new ObjectParameter("type_contractor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddContractor", legal_contractor_addressParameter, account_contractor_supplier_accountParameter, surname_contractorParameter, contractor_nameParameter, contractor_middle_nameParameter, name_organization_contractorParameter, contractor_phoneParameter, type_contractorParameter);
        }
    
        public virtual int AddDelivery_Contract(Nullable<int> delivery_contract_id, Nullable<int> contractor_id, Nullable<System.DateTime> contract_start_date, Nullable<System.DateTime> contract_end_date, Nullable<decimal> contract_cost, Nullable<int> number_of_contract_instances)
        {
            var delivery_contract_idParameter = delivery_contract_id.HasValue ?
                new ObjectParameter("delivery_contract_id", delivery_contract_id) :
                new ObjectParameter("delivery_contract_id", typeof(int));
    
            var contractor_idParameter = contractor_id.HasValue ?
                new ObjectParameter("contractor_id", contractor_id) :
                new ObjectParameter("contractor_id", typeof(int));
    
            var contract_start_dateParameter = contract_start_date.HasValue ?
                new ObjectParameter("contract_start_date", contract_start_date) :
                new ObjectParameter("contract_start_date", typeof(System.DateTime));
    
            var contract_end_dateParameter = contract_end_date.HasValue ?
                new ObjectParameter("contract_end_date", contract_end_date) :
                new ObjectParameter("contract_end_date", typeof(System.DateTime));
    
            var contract_costParameter = contract_cost.HasValue ?
                new ObjectParameter("contract_cost", contract_cost) :
                new ObjectParameter("contract_cost", typeof(decimal));
    
            var number_of_contract_instancesParameter = number_of_contract_instances.HasValue ?
                new ObjectParameter("number_of_contract_instances", number_of_contract_instances) :
                new ObjectParameter("number_of_contract_instances", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddDelivery_Contract", delivery_contract_idParameter, contractor_idParameter, contract_start_dateParameter, contract_end_dateParameter, contract_costParameter, number_of_contract_instancesParameter);
        }
    
        public virtual int AddProduct(string product_id, Nullable<int> measurement_unit_id, Nullable<int> product_type_id, Nullable<int> cell_id, Nullable<int> materials_id, string color_id, string name_of_product, Nullable<int> quantity_of_goods)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var measurement_unit_idParameter = measurement_unit_id.HasValue ?
                new ObjectParameter("measurement_unit_id", measurement_unit_id) :
                new ObjectParameter("measurement_unit_id", typeof(int));
    
            var product_type_idParameter = product_type_id.HasValue ?
                new ObjectParameter("product_type_id", product_type_id) :
                new ObjectParameter("product_type_id", typeof(int));
    
            var cell_idParameter = cell_id.HasValue ?
                new ObjectParameter("cell_id", cell_id) :
                new ObjectParameter("cell_id", typeof(int));
    
            var materials_idParameter = materials_id.HasValue ?
                new ObjectParameter("materials_id", materials_id) :
                new ObjectParameter("materials_id", typeof(int));
    
            var color_idParameter = color_id != null ?
                new ObjectParameter("color_id", color_id) :
                new ObjectParameter("color_id", typeof(string));
    
            var name_of_productParameter = name_of_product != null ?
                new ObjectParameter("name_of_product", name_of_product) :
                new ObjectParameter("name_of_product", typeof(string));
    
            var quantity_of_goodsParameter = quantity_of_goods.HasValue ?
                new ObjectParameter("quantity_of_goods", quantity_of_goods) :
                new ObjectParameter("quantity_of_goods", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProduct", product_idParameter, measurement_unit_idParameter, product_type_idParameter, cell_idParameter, materials_idParameter, color_idParameter, name_of_productParameter, quantity_of_goodsParameter);
        }
    
        public virtual int AddReception_Invoice(Nullable<int> vat_id, Nullable<int> delivery_contract_id, string login_id)
        {
            var vat_idParameter = vat_id.HasValue ?
                new ObjectParameter("vat_id", vat_id) :
                new ObjectParameter("vat_id", typeof(int));
    
            var delivery_contract_idParameter = delivery_contract_id.HasValue ?
                new ObjectParameter("delivery_contract_id", delivery_contract_id) :
                new ObjectParameter("delivery_contract_id", typeof(int));
    
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddReception_Invoice", vat_idParameter, delivery_contract_idParameter, login_idParameter);
        }
    
        public virtual int AddReception_Specification(string product_id, Nullable<int> receipt_id, Nullable<System.DateTime> receipt_date, Nullable<int> quantity_accepted_goods, Nullable<decimal> acceptance_price_values, Nullable<int> contractor_id)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var receipt_idParameter = receipt_id.HasValue ?
                new ObjectParameter("receipt_id", receipt_id) :
                new ObjectParameter("receipt_id", typeof(int));
    
            var receipt_dateParameter = receipt_date.HasValue ?
                new ObjectParameter("receipt_date", receipt_date) :
                new ObjectParameter("receipt_date", typeof(System.DateTime));
    
            var quantity_accepted_goodsParameter = quantity_accepted_goods.HasValue ?
                new ObjectParameter("quantity_accepted_goods", quantity_accepted_goods) :
                new ObjectParameter("quantity_accepted_goods", typeof(int));
    
            var acceptance_price_valuesParameter = acceptance_price_values.HasValue ?
                new ObjectParameter("acceptance_price_values", acceptance_price_values) :
                new ObjectParameter("acceptance_price_values", typeof(decimal));
    
            var contractor_idParameter = contractor_id.HasValue ?
                new ObjectParameter("contractor_id", contractor_id) :
                new ObjectParameter("contractor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddReception_Specification", product_idParameter, receipt_idParameter, receipt_dateParameter, quantity_accepted_goodsParameter, acceptance_price_valuesParameter, contractor_idParameter);
        }
    
        public virtual int AddShipping_Invoice(Nullable<int> vat_id, Nullable<int> delivery_contract_id, string login_id)
        {
            var vat_idParameter = vat_id.HasValue ?
                new ObjectParameter("vat_id", vat_id) :
                new ObjectParameter("vat_id", typeof(int));
    
            var delivery_contract_idParameter = delivery_contract_id.HasValue ?
                new ObjectParameter("delivery_contract_id", delivery_contract_id) :
                new ObjectParameter("delivery_contract_id", typeof(int));
    
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddShipping_Invoice", vat_idParameter, delivery_contract_idParameter, login_idParameter);
        }
    
        public virtual int AddShipping_Specification(string product_id, Nullable<int> shipping_invoice_id, Nullable<System.DateTime> departure_date, Nullable<int> quantity_sent_goods, Nullable<decimal> shipment_price_values)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var shipping_invoice_idParameter = shipping_invoice_id.HasValue ?
                new ObjectParameter("shipping_invoice_id", shipping_invoice_id) :
                new ObjectParameter("shipping_invoice_id", typeof(int));
    
            var departure_dateParameter = departure_date.HasValue ?
                new ObjectParameter("departure_date", departure_date) :
                new ObjectParameter("departure_date", typeof(System.DateTime));
    
            var quantity_sent_goodsParameter = quantity_sent_goods.HasValue ?
                new ObjectParameter("quantity_sent_goods", quantity_sent_goods) :
                new ObjectParameter("quantity_sent_goods", typeof(int));
    
            var shipment_price_valuesParameter = shipment_price_values.HasValue ?
                new ObjectParameter("shipment_price_values", shipment_price_values) :
                new ObjectParameter("shipment_price_values", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddShipping_Specification", product_idParameter, shipping_invoice_idParameter, departure_dateParameter, quantity_sent_goodsParameter, shipment_price_valuesParameter);
        }
    
        public virtual int AddStorekeeper(string login_id, string password_id, string surname_stores, string warehouse_name, string patron_name, string address_ru, byte[] images, Nullable<int> role_id)
        {
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            var password_idParameter = password_id != null ?
                new ObjectParameter("password_id", password_id) :
                new ObjectParameter("password_id", typeof(string));
    
            var surname_storesParameter = surname_stores != null ?
                new ObjectParameter("surname_stores", surname_stores) :
                new ObjectParameter("surname_stores", typeof(string));
    
            var warehouse_nameParameter = warehouse_name != null ?
                new ObjectParameter("warehouse_name", warehouse_name) :
                new ObjectParameter("warehouse_name", typeof(string));
    
            var patron_nameParameter = patron_name != null ?
                new ObjectParameter("patron_name", patron_name) :
                new ObjectParameter("patron_name", typeof(string));
    
            var address_ruParameter = address_ru != null ?
                new ObjectParameter("address_ru", address_ru) :
                new ObjectParameter("address_ru", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("images", images) :
                new ObjectParameter("images", typeof(byte[]));
    
            var role_idParameter = role_id.HasValue ?
                new ObjectParameter("role_id", role_id) :
                new ObjectParameter("role_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddStorekeeper", login_idParameter, password_idParameter, surname_storesParameter, warehouse_nameParameter, patron_nameParameter, address_ruParameter, imagesParameter, role_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CostPrice_Reception(Nullable<int> contractor, string product)
        {
            var contractorParameter = contractor.HasValue ?
                new ObjectParameter("Contractor", contractor) :
                new ObjectParameter("Contractor", typeof(int));
    
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CostPrice_Reception", contractorParameter, productParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CostPrice_Sendings(string product)
        {
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CostPrice_Sendings", productParameter);
        }
    
        public virtual int DeleteContractor(Nullable<int> contractor_id)
        {
            var contractor_idParameter = contractor_id.HasValue ?
                new ObjectParameter("contractor_id", contractor_id) :
                new ObjectParameter("contractor_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteContractor", contractor_idParameter);
        }
    
        public virtual int DeleteDelivery_Contract(Nullable<int> delivery_contract_id)
        {
            var delivery_contract_idParameter = delivery_contract_id.HasValue ?
                new ObjectParameter("delivery_contract_id", delivery_contract_id) :
                new ObjectParameter("delivery_contract_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDelivery_Contract", delivery_contract_idParameter);
        }
    
        public virtual int DeleteProduct(string product_id)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProduct", product_idParameter);
        }
    
        public virtual int DeleteReception_Invoice(Nullable<int> receipt_id, Nullable<System.DateTime> receipt_date)
        {
            var receipt_idParameter = receipt_id.HasValue ?
                new ObjectParameter("receipt_id", receipt_id) :
                new ObjectParameter("receipt_id", typeof(int));
    
            var receipt_dateParameter = receipt_date.HasValue ?
                new ObjectParameter("receipt_date", receipt_date) :
                new ObjectParameter("receipt_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteReception_Invoice", receipt_idParameter, receipt_dateParameter);
        }
    
        public virtual int DeleteReception_Specification(Nullable<int> id_price, string product_id, Nullable<int> receipt_id, Nullable<System.DateTime> receipt_date)
        {
            var id_priceParameter = id_price.HasValue ?
                new ObjectParameter("id_price", id_price) :
                new ObjectParameter("id_price", typeof(int));
    
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var receipt_idParameter = receipt_id.HasValue ?
                new ObjectParameter("receipt_id", receipt_id) :
                new ObjectParameter("receipt_id", typeof(int));
    
            var receipt_dateParameter = receipt_date.HasValue ?
                new ObjectParameter("receipt_date", receipt_date) :
                new ObjectParameter("receipt_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteReception_Specification", id_priceParameter, product_idParameter, receipt_idParameter, receipt_dateParameter);
        }
    
        public virtual int DeleteShipping_Invoice(Nullable<int> shipping_invoice_id, Nullable<System.DateTime> departure_date)
        {
            var shipping_invoice_idParameter = shipping_invoice_id.HasValue ?
                new ObjectParameter("shipping_invoice_id", shipping_invoice_id) :
                new ObjectParameter("shipping_invoice_id", typeof(int));
    
            var departure_dateParameter = departure_date.HasValue ?
                new ObjectParameter("departure_date", departure_date) :
                new ObjectParameter("departure_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteShipping_Invoice", shipping_invoice_idParameter, departure_dateParameter);
        }
    
        public virtual int DeleteShipping_Specification(Nullable<int> id_price, string product_id, Nullable<int> shipping_invoice_id, Nullable<System.DateTime> departure_date)
        {
            var id_priceParameter = id_price.HasValue ?
                new ObjectParameter("id_price", id_price) :
                new ObjectParameter("id_price", typeof(int));
    
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var shipping_invoice_idParameter = shipping_invoice_id.HasValue ?
                new ObjectParameter("shipping_invoice_id", shipping_invoice_id) :
                new ObjectParameter("shipping_invoice_id", typeof(int));
    
            var departure_dateParameter = departure_date.HasValue ?
                new ObjectParameter("departure_date", departure_date) :
                new ObjectParameter("departure_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteShipping_Specification", id_priceParameter, product_idParameter, shipping_invoice_idParameter, departure_dateParameter);
        }
    
        public virtual int DeleteStorekeeper(string login_id, string isDelite)
        {
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            var isDeliteParameter = isDelite != null ?
                new ObjectParameter("IsDelite", isDelite) :
                new ObjectParameter("IsDelite", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteStorekeeper", login_idParameter, isDeliteParameter);
        }
    
        public virtual ObjectResult<FilterContractor_Result> FilterContractor(string type_contractor)
        {
            var type_contractorParameter = type_contractor != null ?
                new ObjectParameter("type_contractor", type_contractor) :
                new ObjectParameter("type_contractor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FilterContractor_Result>("FilterContractor", type_contractorParameter);
        }
    
        public virtual ObjectResult<FilterProduct_Result> FilterProduct(string @new)
        {
            var newParameter = @new != null ?
                new ObjectParameter("New", @new) :
                new ObjectParameter("New", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FilterProduct_Result>("FilterProduct", newParameter);
        }
    
        public virtual ObjectResult<GraphAnalytics_Result> GraphAnalytics(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GraphAnalytics_Result>("GraphAnalytics", yearParameter);
        }
    
        public virtual ObjectResult<GraphAnalytics2_Result> GraphAnalytics2(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GraphAnalytics2_Result>("GraphAnalytics2", yearParameter);
        }
    
        public virtual int ProcExportData(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcExportData", tableNameParameter);
        }
    
        public virtual int ProcImportData(string tableName, string filePath, string fileFormat, string fieldTerminator, string rowTerminator, Nullable<int> firstRow)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var fileFormatParameter = fileFormat != null ?
                new ObjectParameter("fileFormat", fileFormat) :
                new ObjectParameter("fileFormat", typeof(string));
    
            var fieldTerminatorParameter = fieldTerminator != null ?
                new ObjectParameter("fieldTerminator", fieldTerminator) :
                new ObjectParameter("fieldTerminator", typeof(string));
    
            var rowTerminatorParameter = rowTerminator != null ?
                new ObjectParameter("rowTerminator", rowTerminator) :
                new ObjectParameter("rowTerminator", typeof(string));
    
            var firstRowParameter = firstRow.HasValue ?
                new ObjectParameter("firstRow", firstRow) :
                new ObjectParameter("firstRow", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcImportData", tableNameParameter, filePathParameter, fileFormatParameter, fieldTerminatorParameter, rowTerminatorParameter, firstRowParameter);
        }
    
        public virtual ObjectResult<SortrContractor_Result> SortrContractor(Nullable<int> orderby)
        {
            var orderbyParameter = orderby.HasValue ?
                new ObjectParameter("orderby", orderby) :
                new ObjectParameter("orderby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortrContractor_Result>("SortrContractor", orderbyParameter);
        }
    
        public virtual ObjectResult<SortrDelivery_Contract_Result> SortrDelivery_Contract(Nullable<int> orderby)
        {
            var orderbyParameter = orderby.HasValue ?
                new ObjectParameter("orderby", orderby) :
                new ObjectParameter("orderby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortrDelivery_Contract_Result>("SortrDelivery_Contract", orderbyParameter);
        }
    
        public virtual ObjectResult<SortrProduct_Result> SortrProduct(Nullable<int> orderby)
        {
            var orderbyParameter = orderby.HasValue ?
                new ObjectParameter("orderby", orderby) :
                new ObjectParameter("orderby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortrProduct_Result>("SortrProduct", orderbyParameter);
        }
    
        public virtual ObjectResult<SortrReception_Invoice_Result> SortrReception_Invoice(Nullable<int> orderby)
        {
            var orderbyParameter = orderby.HasValue ?
                new ObjectParameter("orderby", orderby) :
                new ObjectParameter("orderby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortrReception_Invoice_Result>("SortrReception_Invoice", orderbyParameter);
        }
    
        public virtual ObjectResult<SortrShipping_Invoice_Result> SortrShipping_Invoice(Nullable<int> orderby)
        {
            var orderbyParameter = orderby.HasValue ?
                new ObjectParameter("orderby", orderby) :
                new ObjectParameter("orderby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortrShipping_Invoice_Result>("SortrShipping_Invoice", orderbyParameter);
        }
    
        public virtual ObjectResult<SortrStorekeeper_Result> SortrStorekeeper(Nullable<int> orderby)
        {
            var orderbyParameter = orderby.HasValue ?
                new ObjectParameter("orderby", orderby) :
                new ObjectParameter("orderby", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SortrStorekeeper_Result>("SortrStorekeeper", orderbyParameter);
        }
    
        public virtual int UPDATE_Delivery_Contract()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Delivery_Contract");
        }
    
        public virtual int UPDATE_Discount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Discount");
        }
    
        public virtual int UpdateContractor(Nullable<int> contractor_id, string legal_contractor_address, string account_contractor_supplier_account, string surname_contractor, string contractor_name, string contractor_middle_name, string name_organization_contractor, string contractor_phone, string type_contractor)
        {
            var contractor_idParameter = contractor_id.HasValue ?
                new ObjectParameter("contractor_id", contractor_id) :
                new ObjectParameter("contractor_id", typeof(int));
    
            var legal_contractor_addressParameter = legal_contractor_address != null ?
                new ObjectParameter("legal_contractor_address", legal_contractor_address) :
                new ObjectParameter("legal_contractor_address", typeof(string));
    
            var account_contractor_supplier_accountParameter = account_contractor_supplier_account != null ?
                new ObjectParameter("account_contractor_supplier_account", account_contractor_supplier_account) :
                new ObjectParameter("account_contractor_supplier_account", typeof(string));
    
            var surname_contractorParameter = surname_contractor != null ?
                new ObjectParameter("surname_contractor", surname_contractor) :
                new ObjectParameter("surname_contractor", typeof(string));
    
            var contractor_nameParameter = contractor_name != null ?
                new ObjectParameter("contractor_name", contractor_name) :
                new ObjectParameter("contractor_name", typeof(string));
    
            var contractor_middle_nameParameter = contractor_middle_name != null ?
                new ObjectParameter("contractor_middle_name", contractor_middle_name) :
                new ObjectParameter("contractor_middle_name", typeof(string));
    
            var name_organization_contractorParameter = name_organization_contractor != null ?
                new ObjectParameter("name_organization_contractor", name_organization_contractor) :
                new ObjectParameter("name_organization_contractor", typeof(string));
    
            var contractor_phoneParameter = contractor_phone != null ?
                new ObjectParameter("contractor_phone", contractor_phone) :
                new ObjectParameter("contractor_phone", typeof(string));
    
            var type_contractorParameter = type_contractor != null ?
                new ObjectParameter("type_contractor", type_contractor) :
                new ObjectParameter("type_contractor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateContractor", contractor_idParameter, legal_contractor_addressParameter, account_contractor_supplier_accountParameter, surname_contractorParameter, contractor_nameParameter, contractor_middle_nameParameter, name_organization_contractorParameter, contractor_phoneParameter, type_contractorParameter);
        }
    
        public virtual int UpdateDelivery_Contract(Nullable<int> delivery_contract_id, Nullable<int> contractor_id, Nullable<System.DateTime> contract_start_date, Nullable<System.DateTime> contract_end_date, Nullable<decimal> contract_cost, Nullable<int> number_of_contract_instances)
        {
            var delivery_contract_idParameter = delivery_contract_id.HasValue ?
                new ObjectParameter("delivery_contract_id", delivery_contract_id) :
                new ObjectParameter("delivery_contract_id", typeof(int));
    
            var contractor_idParameter = contractor_id.HasValue ?
                new ObjectParameter("contractor_id", contractor_id) :
                new ObjectParameter("contractor_id", typeof(int));
    
            var contract_start_dateParameter = contract_start_date.HasValue ?
                new ObjectParameter("contract_start_date", contract_start_date) :
                new ObjectParameter("contract_start_date", typeof(System.DateTime));
    
            var contract_end_dateParameter = contract_end_date.HasValue ?
                new ObjectParameter("contract_end_date", contract_end_date) :
                new ObjectParameter("contract_end_date", typeof(System.DateTime));
    
            var contract_costParameter = contract_cost.HasValue ?
                new ObjectParameter("contract_cost", contract_cost) :
                new ObjectParameter("contract_cost", typeof(decimal));
    
            var number_of_contract_instancesParameter = number_of_contract_instances.HasValue ?
                new ObjectParameter("number_of_contract_instances", number_of_contract_instances) :
                new ObjectParameter("number_of_contract_instances", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDelivery_Contract", delivery_contract_idParameter, contractor_idParameter, contract_start_dateParameter, contract_end_dateParameter, contract_costParameter, number_of_contract_instancesParameter);
        }
    
        public virtual int UpdateProduct(string product_id, Nullable<int> materials_id, string color_id, Nullable<int> measurement_unit_id, Nullable<int> product_type_id, Nullable<int> cell_id, string name_of_product, Nullable<int> quantity_of_goods)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var materials_idParameter = materials_id.HasValue ?
                new ObjectParameter("materials_id", materials_id) :
                new ObjectParameter("materials_id", typeof(int));
    
            var color_idParameter = color_id != null ?
                new ObjectParameter("color_id", color_id) :
                new ObjectParameter("color_id", typeof(string));
    
            var measurement_unit_idParameter = measurement_unit_id.HasValue ?
                new ObjectParameter("measurement_unit_id", measurement_unit_id) :
                new ObjectParameter("measurement_unit_id", typeof(int));
    
            var product_type_idParameter = product_type_id.HasValue ?
                new ObjectParameter("product_type_id", product_type_id) :
                new ObjectParameter("product_type_id", typeof(int));
    
            var cell_idParameter = cell_id.HasValue ?
                new ObjectParameter("cell_id", cell_id) :
                new ObjectParameter("cell_id", typeof(int));
    
            var name_of_productParameter = name_of_product != null ?
                new ObjectParameter("name_of_product", name_of_product) :
                new ObjectParameter("name_of_product", typeof(string));
    
            var quantity_of_goodsParameter = quantity_of_goods.HasValue ?
                new ObjectParameter("quantity_of_goods", quantity_of_goods) :
                new ObjectParameter("quantity_of_goods", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProduct", product_idParameter, materials_idParameter, color_idParameter, measurement_unit_idParameter, product_type_idParameter, cell_idParameter, name_of_productParameter, quantity_of_goodsParameter);
        }
    
        public virtual int UpdateReception_Invoice(Nullable<int> receipt_id, Nullable<int> vat_id, Nullable<int> delivery_contract_id, string login_id, Nullable<System.DateTime> receipt_date)
        {
            var receipt_idParameter = receipt_id.HasValue ?
                new ObjectParameter("receipt_id", receipt_id) :
                new ObjectParameter("receipt_id", typeof(int));
    
            var vat_idParameter = vat_id.HasValue ?
                new ObjectParameter("vat_id", vat_id) :
                new ObjectParameter("vat_id", typeof(int));
    
            var delivery_contract_idParameter = delivery_contract_id.HasValue ?
                new ObjectParameter("delivery_contract_id", delivery_contract_id) :
                new ObjectParameter("delivery_contract_id", typeof(int));
    
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            var receipt_dateParameter = receipt_date.HasValue ?
                new ObjectParameter("receipt_date", receipt_date) :
                new ObjectParameter("receipt_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateReception_Invoice", receipt_idParameter, vat_idParameter, delivery_contract_idParameter, login_idParameter, receipt_dateParameter);
        }
    
        public virtual int UpdateReception_Specification(string product_id, Nullable<int> receipt_id, Nullable<System.DateTime> receipt_date, Nullable<int> quantity_accepted_goods)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var receipt_idParameter = receipt_id.HasValue ?
                new ObjectParameter("receipt_id", receipt_id) :
                new ObjectParameter("receipt_id", typeof(int));
    
            var receipt_dateParameter = receipt_date.HasValue ?
                new ObjectParameter("receipt_date", receipt_date) :
                new ObjectParameter("receipt_date", typeof(System.DateTime));
    
            var quantity_accepted_goodsParameter = quantity_accepted_goods.HasValue ?
                new ObjectParameter("quantity_accepted_goods", quantity_accepted_goods) :
                new ObjectParameter("quantity_accepted_goods", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateReception_Specification", product_idParameter, receipt_idParameter, receipt_dateParameter, quantity_accepted_goodsParameter);
        }
    
        public virtual int UpdateShipping_Invoice(Nullable<int> shipping_invoice_id, Nullable<int> vat_id, Nullable<int> delivery_contract_id, string login_id, Nullable<System.DateTime> departure_date)
        {
            var shipping_invoice_idParameter = shipping_invoice_id.HasValue ?
                new ObjectParameter("shipping_invoice_id", shipping_invoice_id) :
                new ObjectParameter("shipping_invoice_id", typeof(int));
    
            var vat_idParameter = vat_id.HasValue ?
                new ObjectParameter("vat_id", vat_id) :
                new ObjectParameter("vat_id", typeof(int));
    
            var delivery_contract_idParameter = delivery_contract_id.HasValue ?
                new ObjectParameter("delivery_contract_id", delivery_contract_id) :
                new ObjectParameter("delivery_contract_id", typeof(int));
    
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            var departure_dateParameter = departure_date.HasValue ?
                new ObjectParameter("departure_date", departure_date) :
                new ObjectParameter("departure_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateShipping_Invoice", shipping_invoice_idParameter, vat_idParameter, delivery_contract_idParameter, login_idParameter, departure_dateParameter);
        }
    
        public virtual int UpdateShipping_Specification(string product_id, Nullable<int> shipping_invoice_id, Nullable<System.DateTime> departure_date, Nullable<int> quantity_sent_goods)
        {
            var product_idParameter = product_id != null ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(string));
    
            var shipping_invoice_idParameter = shipping_invoice_id.HasValue ?
                new ObjectParameter("shipping_invoice_id", shipping_invoice_id) :
                new ObjectParameter("shipping_invoice_id", typeof(int));
    
            var departure_dateParameter = departure_date.HasValue ?
                new ObjectParameter("departure_date", departure_date) :
                new ObjectParameter("departure_date", typeof(System.DateTime));
    
            var quantity_sent_goodsParameter = quantity_sent_goods.HasValue ?
                new ObjectParameter("quantity_sent_goods", quantity_sent_goods) :
                new ObjectParameter("quantity_sent_goods", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateShipping_Specification", product_idParameter, shipping_invoice_idParameter, departure_dateParameter, quantity_sent_goodsParameter);
        }
    
        public virtual int UpdateStorekeeper(string login_id, string password_id, string surname_stores, string warehouse_name, string patron_name, string address_ru, byte[] images, Nullable<int> role_id)
        {
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            var password_idParameter = password_id != null ?
                new ObjectParameter("password_id", password_id) :
                new ObjectParameter("password_id", typeof(string));
    
            var surname_storesParameter = surname_stores != null ?
                new ObjectParameter("surname_stores", surname_stores) :
                new ObjectParameter("surname_stores", typeof(string));
    
            var warehouse_nameParameter = warehouse_name != null ?
                new ObjectParameter("warehouse_name", warehouse_name) :
                new ObjectParameter("warehouse_name", typeof(string));
    
            var patron_nameParameter = patron_name != null ?
                new ObjectParameter("patron_name", patron_name) :
                new ObjectParameter("patron_name", typeof(string));
    
            var address_ruParameter = address_ru != null ?
                new ObjectParameter("address_ru", address_ru) :
                new ObjectParameter("address_ru", typeof(string));
    
            var imagesParameter = images != null ?
                new ObjectParameter("images", images) :
                new ObjectParameter("images", typeof(byte[]));
    
            var role_idParameter = role_id.HasValue ?
                new ObjectParameter("role_id", role_id) :
                new ObjectParameter("role_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStorekeeper", login_idParameter, password_idParameter, surname_storesParameter, warehouse_nameParameter, patron_nameParameter, address_ruParameter, imagesParameter, role_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VIEWContractor_id(Nullable<int> iD, Nullable<System.DateTime> iD2)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD2Parameter = iD2.HasValue ?
                new ObjectParameter("ID2", iD2) :
                new ObjectParameter("ID2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VIEWContractor_id", iDParameter, iD2Parameter);
        }
    
        public virtual ObjectResult<string> VIEWMail(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("VIEWMail", loginParameter);
        }
    
        public virtual ObjectResult<VIEWReception_Specification_Result> VIEWReception_Specification(Nullable<int> iD, Nullable<System.DateTime> iD2)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD2Parameter = iD2.HasValue ?
                new ObjectParameter("ID2", iD2) :
                new ObjectParameter("ID2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIEWReception_Specification_Result>("VIEWReception_Specification", iDParameter, iD2Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> VIEWRole(string login_id, string password)
        {
            var login_idParameter = login_id != null ?
                new ObjectParameter("login_id", login_id) :
                new ObjectParameter("login_id", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("VIEWRole", login_idParameter, passwordParameter);
        }
    
        public virtual ObjectResult<VIEWShipping_Specification_Result> VIEWShipping_Specification(Nullable<int> iD, Nullable<System.DateTime> iD2)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD2Parameter = iD2.HasValue ?
                new ObjectParameter("ID2", iD2) :
                new ObjectParameter("ID2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VIEWShipping_Specification_Result>("VIEWShipping_Specification", iDParameter, iD2Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ValueProduct(string product)
        {
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ValueProduct", productParameter);
        }
    }
}
