//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Sendings
    {
        public int shipment_price_id { get; set; }
        public decimal shipment_price_values { get; set; }
        public System.DateTime send_price_date { get; set; }
        public string product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
