//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Price_Reception = new HashSet<Price_Reception>();
            this.Price_Sendings = new HashSet<Price_Sendings>();
            this.Reception_Specification = new HashSet<Reception_Specification>();
            this.Shipping_Specification = new HashSet<Shipping_Specification>();
        }
    
        public string product_id { get; set; }
        public int measurement_unit_id { get; set; }
        public int product_type_id { get; set; }
        public int cell_id { get; set; }
        public int materials_id { get; set; }
        public string color_id { get; set; }
        public string name_of_product { get; set; }
        public int quantity_of_goods { get; set; }
    
        public virtual Color_object Color_object { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Measurement Measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Reception> Price_Reception { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price_Sendings> Price_Sendings { get; set; }
        public virtual Product_Location_Cell Product_Location_Cell { get; set; }
        public virtual Product_type Product_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception_Specification> Reception_Specification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping_Specification> Shipping_Specification { get; set; }
    }
}
