//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception_Specification
    {
        public string product_id { get; set; }
        public int receipt_id { get; set; }
        public System.DateTime receipt_date { get; set; }
        public int quantity_accepted_goods { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Reception_Invoice Reception_Invoice { get; set; }
        public virtual Reception_Invoice Reception_Invoice1 { get; set; }
    }
}
