//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_Specification
    {
        public Nullable<int> discount_id { get; set; }
        public string product_id { get; set; }
        public int shipping_invoice_id { get; set; }
        public System.DateTime departure_date { get; set; }
        public int quantity_sent_goods { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shipping_Invoice Shipping_Invoice { get; set; }
        public virtual Shipping_Invoice Shipping_Invoice1 { get; set; }
    }
}
