//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storekeeper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storekeeper()
        {
            this.Reception_Invoice = new HashSet<Reception_Invoice>();
            this.Shipping_Invoice = new HashSet<Shipping_Invoice>();
        }
    
        public string login_id { get; set; }
        public string password_id { get; set; }
        public string surname_stores { get; set; }
        public string warehouse_name { get; set; }
        public string patron_name { get; set; }
        public string address_ru { get; set; }
        public byte[] images { get; set; }
        public int role_id { get; set; }
        public string IsDelite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception_Invoice> Reception_Invoice { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipping_Invoice> Shipping_Invoice { get; set; }
    }
}
