//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWProduct2
    {
        public string ID { get; set; }
        public string ед_из { get; set; }
        public string Наименование { get; set; }
        public string Тип { get; set; }
        public string Материал { get; set; }
        public string Цвет { get; set; }
    }
}
