//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWDelivery_Contract
    {
        public int ID { get; set; }
        public string Расчетный_счет { get; set; }
        public string Наименование_организации { get; set; }
        public string Заказчик_Поставщик { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public System.DateTime Дата_окончания { get; set; }
        public decimal Стоимость_договора { get; set; }
        public int Количество_экземпляров { get; set; }
        public string Валидность { get; set; }
    }
}
