//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dikom.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWReception_Invoice
    {
        public int Номер_накладной { get; set; }
        public System.DateTime Дата_накладной { get; set; }
        public string Наименование_организации { get; set; }
        public string НДС_на_товар { get; set; }
        public string Принял_накладную { get; set; }
    }
}
